### ISSUE TITLE
Questions on the current state

### ISSUE THREAD

**Issue by tomitrescak** [nodee-apps/testisimo#5]
This weekend I need to do a bunch of tests for my app and would love to use this tool. Before I would like to know several things:

1. Where are the tests stored and how can they be saved to a secure location
2. What is the state of CI? 
3. How can I add new test items? What is the API? I already see I miss some that I would need to have for my testing, such as calls to standard Meteor API, assertions on URL and more. How difficult is to add a new item? I would love to see a method that would allow me to register custom asserion items in which I design UI and assertion logics via standard API.

**Comment by matusszabo** [comment]
Hi @tomitrescak ,

1. Testisimo has no backend yet, tests are stored in browser local storage, so until you clear browser cache, tests will be stored there - you can export project as json, and import it back

2. CI integration is in development, today it can be run only manually

3. If you mean custom action, yes there is way to add it, please take a look at actions, e.g. https://github.com/nodee-apps/testisimo/blob/master/src/actions/click.js (optsPreview will be removed due to UI changes). Can you describe actions you need ? I can help you develop custom one.

**Comment by tomitrescak** [comment]
@matusszabo I went over the current state and I like the changes. It took me a bit of time to understand where can I do stuff, but after 5-10 minutes all was clear.

Concerning custom actions I need to be able to:

1. Execute custom javascript: e.g. to insert fixtures to the database (or just to execute a fnction with parameters that resides in "global")
2. Execute meteor methods, that is I need to be able to specify a name of the method and its parameters

So, the question is, how can I add these controls to your UI? That is textboxes and possibly some comboboxes?

Thanks

**Comment by matusszabo** [comment]
Hi @tomitrescak , thank you, UI is still on the way to be simple as possible. Most similar action is https://github.com/nodee-apps/testisimo/blob/master/src/actions/location.js .

How to:

1. create new action object: Testisimo.prototype.actions.<yourActionID>

2. name - the name in actions dropdown in UI (auto ordered by name)

3. optsTemplate - angular template, in which action.opts is action options :) '<input type="text" class="input-variable" placeholder="/mypath" ng-model="action.opts.location">'

4. optsVariables - list of opts properties in which will testisimo search for variables in brackets like {myvar}, therefore it should be string

5. handler - action handler, this method will run when action is called, with arguments targets (target list if parsed elements attributes, and elements, try to console.log it, you will see structure), opts (action.opts filled by UI in optsTemplate), variables (test variables object), done (allways call done when action ends, it has only one argument Error, message of This Error will be shown in UI if action fails)

6. just put this action definition after <script src="https://rawgit.com/nodejs-enterprise/testisimo/master/testisimo.js"></script> it should work

Let me know your progress, thank you.
